Add and Remove
Bantealem/my-to-do-list pull request #1
Opened 2022-08-22 12:44 UTC by Bantealem

I have made add and remove website for to list

2022-08-22 13:32 UTC, vechicin requested changes
# Hi @Bantealem ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good job implementing most of the features for this milestone

## Required Changes ♻️

- [ ] Be mindful of the way you are setting up linters. When I ran the `npx eslint .` locally, I got this error.
<img width="573" alt="Screen Shot 2022-08-22 at 8 30 33" src="https://user-images.githubusercontent.com/82426682/185933078-ac23fb49-8394-4d2a-b8de-23e88fd688ac.png">

Please be mindful of **NOT EDITING** the config files if this is what caused the issue.

_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-22 13:32 UTC, vechicin commented on src/modules/actions.js
> +  };
I cannot edit a task. Please fix this issue.

2022-08-22 13:32 UTC, vechicin commented on src/index.js
> +/* eslint-disable no-plusplus */
Please do not disable ESLint rules.

2022-08-22 13:32 UTC, vechicin commented on src/modules/actions.js
> +/* eslint-disable no-plusplus */
Please do not disable ESLint rules.

2022-08-22 13:32 UTC, vechicin commented on src/modules/helpers.js
> +/* eslint-disable no-plusplus */
Please do not disable ESLint rules.

2022-08-22 13:32 UTC, vechicin commented on src/modules/taskStatus.js
> +/* eslint-disable no-plusplus */
Please do not disable ESLint rules.

2022-08-23 09:15 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @Bantealem 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great job on implementing CRUD operations ✅
- Use ES6 modules to write modular JavaScript. ✅
- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions

- [OPTIONAL] I suggest adding the Link to your `License` file in your READM file 💯

> The MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. 💯

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 09:15 UTC, Bondok6 commented on README.md
> +# Awesome Books
- [OPTIONAL] I suggest changing the name of the project to To Do List. 👌💯

2022-08-23 21:45 UTC, merged

2022-12-11 13:53 UTC, Bantealem commented
Bantealem/space-travelers-hub